# Generated by Django 5.2 on 2025-05-01 19:44

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[250, 250], upload_to='airplanes/'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='airplanetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
