# Generated by Django 5.2 on 2025-05-02 14:17

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_airplane_photo_alter_airplane_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='airplane',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='airplanes/'),
        ),
    ]
