# Generated by Django 5.2 on 2025-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_alter_airplane_options_alter_airplanetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='category',
            field=models.CharField(blank=True, choices=[('Passenger', 'Passenger'), ('Private', 'Private'), ('Cargo', 'Cargo')], max_length=20, null=True),
        ),
    ]
