services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django-rest
    image: kram3ko/airport
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      # no sync for production
      - ./:/app
      - airport_media:/files/media
      - airport_static:/files/static
    depends_on:
      airport_db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/sites-available/airplane.conf:/etc/nginx/conf.d/airplane.conf:ro
      - airport_media:/files/media
      - airport_static:/files/static
    ports:
      - "80:80"
    depends_on:
      - django

  airport_db:
    image: postgres:alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - airport_db:$PGDATA

volumes:
  airport_db:
    name: airport_db
  airport_media:
    name: airport_media
  airport_static:
    name: airport_static