# Generated by Django 5.2 on 2025-05-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('closest_big_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'city', 'country'), name='unique_airport_name_city_country')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('flight_number', models.CharField(max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='airports.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_airport', to='airports.airport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'destination', 'flight_number'), name='unique_route')],
            },
        ),
    ]
