# Generated by Django 5.2 on 2025-05-06 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name'], 'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['flight_number'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='airports.airport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Distance must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='flight_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='airports.airport'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['name'], name='airports_ai_name_b30727_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city'], name='airports_ai_city_d30040_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country'], name='airports_ai_country_3d1a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['flight_number'], name='airports_ro_flight__05524c_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('destination')), _negated=True), name='different_source_destination'),
        ),
    ]
