# Generated by Django 5.2 on 2025-05-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_alter_airport_options_alter_route_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='different_source_destination',
        ),
    ]
